hello: hello.c cs50.c
		gcc $^ -o $@

compare: compare.c cs50.c
		gcc $^ -o $@

agree: agree.c cs50.c
		gcc $^ -o $@

mario: mario.c cs50.c
		gcc $^ -o $@

calculator: calculator.c cs50.c
		gcc $^ -o $@