readability: readability.c cs50.c math.c
		gcc $^ -o $@

bulbs: bulbs.c cs50.c
		gcc $^ -o $@

caesar: caesar.c cs50.c
		gcc $^ -o $@

substitution: substitution.c cs50.c
		gcc $^ -o $@

wordle: wordle.c cs50.c
		gcc $^ -o $@
